### ISSUE TITLE
MySQL installation issue w/Docker

### ISSUE THREAD

**Issue by docent-net** [pimcore/docker-pimcore-demo-standalone#1]
Guys,

Just installed pimcore using Docker image pulled from pimcore/docker-pimcore-demo-standalone

After starting container I noticed that I can't login to the admin panel (wrong login / pwd).

From container logs I concluded that installator has issues with database scripts. While importing 'data.sql' we got:

```ERROR 1146 (42S02) at line 373: Table 'pimcore_demo_pimcore.assets' doesn't exist```

After a while of poking around I resolved this with very nasty way:

```
mysql -u pimcore_demo -psecretpassword pimcore_demo_pimcore < pimcore/modules/install/mysql/install.sql

mysql -u pimcore_demo -psecretpassword pimcore_demo_pimcore < /var/www/website/dump/data.sql
```

This way I made sure that all the tables are created by the original install.sql and afterwards I run the data.sql in order to import the rest of the data.

So for now running Docker container will bring user to unusable Pimcore installation.

Cheers,

**Comment by brusch** [comment]
Thank you very much.
There was recently a change in the way the setup is done in pimcore, and the docker image wasn't updated yet.
