### ISSUE TITLE
Why you don't tag your versions?

### ISSUE THREAD

**Issue by timaschew** [pimcore/docker-pimcore-demo-standalone#8]
I want to setup an old version pimcore 3 with docker, but you didn't tag the versionsn and overwrite always `latest`

**Comment by brusch** [comment]
... because this docker image is only for demo purposes **NOT ** for production. 
Please use our setup as a reference to create your own production-ready configuration.

**Comment by brusch** [comment]
see also the repo name: docker-pimcore-**demo**-standalone ;-)

**Comment by timaschew** [comment]
It's not for production, it's for development.

**Comment by brusch** [comment]
Anyway, this Dockerfile is only for demo purposes.
